### ISSUE TITLE
Problem with leastest version (Connection)

### ISSUE THREAD

**Issue by fightmaxime** [HexagonMC/BungeeCord#139]
### What Hexacord version are you using? Post the output of /bungee
v134
v135

### Are you using Bungee plugins? If yes, please list all of them + versionnumber
NO

### How can we reproduce the error/bug? 
Use Forge  1.8-Forge11.14.1.1334

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
https://pastebin.com/QMEiHXyM

### In addidtion to that, please explain your issue as detailed as possible.
Check the pastebin, I have comback to v132 and that fixed

**Comment by Eufranio** [comment]
```
14:31:52 [SEVERE] Apr 25, 2017 2:31:52 PM io.netty.util.concurrent.AbstractEventExecutor safeExecute
WARNING: A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@382f34fc
java.lang.NullPointerException
    at net.md_5.bungee.UserConnection.init(UserConnection.java:199)
    at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:498)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by dualspiral** [comment]
> Use Forge 1.8-Forge11.14.1.1334

**That's nowhere near the latest version.** I originally built this IP forwarding system for Sponge on 1.8, so I know it works, but your clients need to be using _later_ Forge versions.

The problem is that earlier versions of Forge didn't seem to send the profile properly, 1507+ by my reckoning (though I've not done a through search) will probably fix this. The NPE is fired because the `profile` variable is null.

I suppose I could try to make a login profile if it doesn't exist.

**Comment by Eufranio** [comment]
We use the HexagonMC BungeeCord because it supports since 1.7 to 1.10 clients, and my error (that I just posted) was from 1.10 clients trying to log in...

**Comment by dualspiral** [comment]
Well then please _say that up front_. I assumed that your error was from 1.8 too, because of the original report suggesting it was this. Your stack trace gave me _no additional information_ and led me to assume it was because old versions were being used.

Looking into it further, I'm possibly wrong - but then I have no idea why the login profile is null, but it _certainly shouldn't be_. [It's failing here](https://github.com/HexagonMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/UserConnection.java#L199) - `profile` is null. But, in order to create the `UserConnection` object in online mode, [the `LoginResult` should be non-null](https://github.com/HexagonMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/connection/InitialHandler.java#L416-L424) - which calls `finish()` - calling [the constructor here](https://github.com/HexagonMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/connection/InitialHandler.java#L496).

So, I don't fully understand what is going on, but something isn't setting the profile properly.

**Comment by fightmaxime** [comment]
Now v139 (Only with my forge 11.14.1.1334)
22:37:01 [INFO] [fightmaxime] <-> ServerConnector [lobby1] has connected
22:37:01 [INFO] [fightmaxime] disconnected with: ?cKicked whilst connecting to lobby1: ?fIf you wish to use IP forwarding, please enable it in your BungeeCord config as well!
22:37:01 [INFO] [fightmaxime] <-> ServerConnector [lobby1] has disconnected
22:37:02 [INFO] [fightmaxime] -> UpstreamBridge has disconnected
