### ISSUE TITLE
Cant connect to server with 1.9+ | Critical

### ISSUE THREAD

**Issue by SnakeDaoust1232** [HexagonMC/BungeeCord#163]
### What Hexacord version are you using? Post the output of /bungee
https://gyazo.com/f3170b8ef6fbda3ec206b4c9a0cf9484

### Are you using Bungee plugins? If yes, please list all of them + versionnumber
none

### How can we reproduce the error/bug? 
join

### Is an error message (bungee/spigot/client)? If yes, use pastebin.com and share the link.
https://gyazo.com/7a5239a966c2e35663f15b6547cbc907

### In addidtion to that, please explain your issue as detailed as possible.
Trying to connect to a tacospigot 1.8.8 server with any client above 1.8 doesn't work. 

ProtocolSupport: http://myles.us/ViaVersion/ProtocolSupport1.8.8.jar
ViaVersion: https://www.spigotmc.org/resources/viaversion.19254/
TacoSpigot: https://ci.techcable.net/job/TacoSpigot-1.8.8/

More info:
- I've tried downgrading to v141 and then v132. And it didn't help.

**Comment by SnakeDaoust1232** [comment]
@i9hdkill @ghacproductions @Zartec Please fix :(

**Comment by popcorn9499** [comment]
since your running a 1.8.8 server does this work when u dont have the bungee in the loop so try without bungee. That would be something id check. Another thing I'd check is running normal spigot 1.8.8 I have built this a long time ago from when I used spigot 1.8.8 So id recommend checking against a version of spigot 1.8.8 Here is a link to my copy [URL](https://popicraft.net/jenkins/job/Spigot%201.8.8/) hopefully we can figure it out. I am using spigot 1.11.2 and protocol support and viaversion and Ive found it works perfectly fine and I used to use 1.8.8 for my hub as well before i used protocol support and trusted it. so im currious to see if using regular spigot or without the bungee fixes it

**Comment by SnakeDaoust1232** [comment]
Yeah it works fine without bungee. As soon as i put the server behind bungee, it doesnt work.

**Comment by popcorn9499** [comment]
Can u try running it with regular spigot and regular bungeecord?

**Comment by SnakeDaoust1232** [comment]
It works fine with normal spigot. Its only tacospigot. But tacospigot isnt blocking it. Hexacord just needs to add support for tacospigot.

**Comment by ghacproductions** [comment]
Does it work with normal BungeeCord? @SnakeDaoust1232

**Comment by SnakeDaoust1232** [comment]
What would i be testing with normal bungeecord?It doesnt have protocol hacks. Give me the settup you want me to test, and when i get home, ill test it and report back.

**Comment by ghacproductions** [comment]
The original support has 1.8-1.12-support, so please test if the error occurs with the original BungeeCord.

**Comment by SnakeDaoust1232** [comment]
Yeah. I cant connect with original bungeecord either.

**Comment by i9hdkill** [comment]
Wen won't add support for weird spigot branches. Use original spigot or paper.

**Comment by SnakeDaoust1232** [comment]
@i9hdkill TacoSpigot was made by the creator of PaperSpigot. Its a performance version of PaperSpigot for factions servers. All HUGE factions server user it.

**Comment by ghacproductions** [comment]
As this occurs with original BungeeCord as well, you have to ask them for support.

**Comment by SnakeDaoust1232** [comment]
@i9hdkill @ghacproductions Just to let you guys know, for anyone else that may have my issue as well... i had latebind set to true, it needs to be set to false. Then everything works fine.
